import type { DashboardConfig } from "../types/dashboard";

export const dashboardConfig: DashboardConfig = {
  app: {
    name: "Living Dashboard",
    locale: "ja-JP",
    timezone: "Asia/Tokyo",
    defaultDisplayMode: "home",
    autoReload: {
      enabled: true,
      intervalMinutes: 360,
    },
  },
  layout: {
    type: "living-room-landscape",
    gapPx: 12,
    paddingPx: 16,
  },
  theme: {
    mode: "dark",
    density: "comfortable",
    fontScale: 1,
    enableBurnInProtection: true,
  },
  widgets: [
    {
      id: "weather-main",
      type: "weather",
      title: "Weather",
      enabled: true,
      size: "large",
      refreshIntervalSec: 1800,
      order: 1,
      area: "main-left",
      settings: {
        provider: "openMeteo",
        latitude: 35.6812,
        longitude: 139.7671,
        locationName: "Tokyo",
        units: "metric",
        showTomorrow: true,
        showHumidity: true,
        showWind: false,
      },
    },
    {
      id: "calendar-main",
      type: "calendar",
      title: "Calendar",
      enabled: true,
      size: "large",
      refreshIntervalSec: 600,
      order: 2,
      area: "main-right",
      settings: {
        provider: "mock",
        daysAhead: 2,
        maxTodayEvents: 4,
        maxTomorrowEvents: 2,
        showAllDayEvents: true,
      },
    },
    {
      id: "stocks-main",
      type: "stocks",
      title: "Markets",
      enabled: false,
      size: "medium",
      refreshIntervalSec: 600,
      order: 3,
      area: "sub-left",
      settings: {
        provider: "mock",
        symbols: ["^N225", "^IXIC", "^GSPC", "USDJPY=X"],
        maxItems: 5,
        showCurrency: true,
        showMarketState: true,
      },
    },
    {
      id: "traffic-main",
      type: "traffic",
      title: "Traffic",
      enabled: true,
      size: "medium",
      refreshIntervalSec: 300,
      order: 3,
      area: "sub-left",
      settings: {
        provider: "mock",
        // MVP keeps the registered route list in config. A future settings UI can override this per device via localStorage
        // without requiring two-way server sync from GitHub Pages.
        lines: [
          { id: "jr-chuo-rapid", name: "中央線快速", operator: "JR東日本", priority: 1 },
          { id: "tokyo-metro-tozai", name: "東京メトロ東西線", operator: "東京メトロ", priority: 2 },
          { id: "jr-yamanote", name: "山手線", operator: "JR東日本", priority: 3 },
          { id: "jr-sobu-local", name: "総武線各駅停車", operator: "JR東日本", priority: 4 },
          { id: "tokyo-metro-marunouchi", name: "丸ノ内線", operator: "東京メトロ", priority: 5 },
          { id: "tokyo-metro-ginza", name: "銀座線", operator: "東京メトロ", priority: 6 },
          { id: "keio-line", name: "京王線", operator: "京王電鉄", priority: 7 },
          { id: "keio-inokashira", name: "京王井の頭線", operator: "京王電鉄", priority: 8 },
        ],
        maxItems: 8,
        showLineUpdatedAt: true,
        allowLocalOverride: true,
      },
    },
    {
      id: "news-main",
      type: "news",
      title: "News",
      enabled: true,
      size: "medium",
      refreshIntervalSec: 1800,
      order: 4,
      area: "sub-right",
      settings: {
        provider: "mock",
        feeds: [
          { id: "nhk", name: "NHK" },
          { id: "itmedia", name: "ITmedia" },
          { id: "hackernews", name: "Hacker News" },
        ],
        maxItems: 5,
        showSource: true,
        showPublishedAt: true,
      },
    },
    {
      id: "pet-photo-main",
      type: "petPhoto",
      title: "今日のぐり",
      enabled: true,
      size: "medium",
      refreshIntervalSec: 43200,
      order: 5,
      area: "sub-right",
      settings: {
        provider: "staticManifest",
        manifestPath: "/pets/manifest.json",
        selection: "twiceDaily",
      },
    },
  ],
  commands: {
    enabled: false,
    acceptedSources: ["alexa", "webhook", "manual"],
    defaultTimeoutSec: 300,
  },
};
