import type { DashboardConfig } from "../types/dashboard";

export const dashboardConfig: DashboardConfig = {
  app: {
    name: "Living Dashboard",
    locale: "ja-JP",
    timezone: "Asia/Tokyo",
    defaultDisplayMode: "home",
    autoReload: {
      enabled: true,
      intervalMinutes: 360,
    },
  },
  layout: {
    type: "living-room-landscape",
    gapPx: 12,
    paddingPx: 16,
  },
  theme: {
    mode: "dark",
    density: "comfortable",
    fontScale: 1,
    enableBurnInProtection: true,
  },
  widgets: [
    {
      id: "weather-main",
      type: "weather",
      title: "Weather",
      enabled: true,
      size: "large",
      refreshIntervalSec: 1800,
      order: 1,
      area: "main-left",
      settings: {
        provider: "openMeteo",
        latitude: 35.6812,
        longitude: 139.7671,
        locationName: "Tokyo",
        units: "metric",
        showTomorrow: true,
        showHumidity: true,
        showWind: false,
      },
    },
    {
      id: "calendar-main",
      type: "calendar",
      title: "Calendar",
      enabled: true,
      size: "large",
      refreshIntervalSec: 600,
      order: 2,
      area: "main-right",
      settings: {
        provider: "mock",
        daysAhead: 2,
        maxTodayEvents: 4,
        maxTomorrowEvents: 2,
        showAllDayEvents: true,
      },
    },
    {
      id: "stocks-main",
      type: "stocks",
      title: "Markets",
      enabled: true,
      size: "medium",
      refreshIntervalSec: 600,
      order: 3,
      area: "sub-left",
      settings: {
        provider: "mock",
        symbols: ["^N225", "^IXIC", "^GSPC", "USDJPY=X"],
        maxItems: 5,
        showCurrency: true,
        showMarketState: true,
      },
    },
    {
      id: "news-main",
      type: "news",
      title: "News",
      enabled: true,
      size: "medium",
      refreshIntervalSec: 1800,
      order: 4,
      area: "sub-right",
      settings: {
        provider: "mock",
        feeds: [
          { id: "nhk", name: "NHK" },
          { id: "itmedia", name: "ITmedia" },
          { id: "hackernews", name: "Hacker News" },
        ],
        maxItems: 5,
        showSource: true,
        showPublishedAt: true,
      },
    },
    {
      id: "quick-area-main",
      type: "quickArea",
      title: "Quick",
      enabled: true,
      size: "wide",
      refreshIntervalSec: 0,
      order: 5,
      area: "quick-area",
      settings: {
        buttons: [
          { label: "Home", displayMode: "home" },
          { label: "Weather", displayMode: "weather" },
          { label: "Calendar", displayMode: "calendar" },
          { label: "News", displayMode: "news" },
          { label: "Markets", displayMode: "stocks" },
        ],
      },
    },
  ],
  commands: {
    enabled: false,
    acceptedSources: ["alexa", "webhook", "manual"],
    defaultTimeoutSec: 300,
  },
};
